class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.50.tar.gz"
  sha256 "a76b8c5aeba214da8046a96950b3b3d455816a558f32b28a5f4cd926e6f90d38"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "837a69ee59771b528eba55f71d3691690d18b7104cc37a9356e257ed208853df"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "837a69ee59771b528eba55f71d3691690d18b7104cc37a9356e257ed208853df"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "837a69ee59771b528eba55f71d3691690d18b7104cc37a9356e257ed208853df"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "4b2c7ca31fc014859196f27b0feaebe7055e45a534e470206312160a355b4d91"
    sha256 cellar: :any,                 x86_64_linux:  "86d8d9232b43ad7ca710c7cde85da97d74b08ec9b0df005d7153d6e3ebc16782"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
